- name: "Install {{ data | default(service + '/data') }}/genesis.json"
  become_user: root
  become: true
  copy:
    src: "{{ data | default(service + '/data') }}/genesis.json"
    dest: "/home/{{ service }}/.{{ service }}/config/genesis.json"
    owner: "{{ service }}"
    group: "{{ service }}"
    mode: 0644

- name: Set proxy_app
  lineinfile:
    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
    state: present
    regexp: '^proxy_app *='
    line: 'proxy_app = "kvstore"'

- name: Set block commit cadence
  lineinfile:
    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
    state: present
    regexp: '^timeout_commit *='
    line: 'timeout_commit = "{{ BLOCK_CADENCE }}"'

- name: Set persistent_peers
  lineinfile:
    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
    state: present
    regexp: '^persistent_peers *='
    line: 'persistent_peers = "{{ PERSISTENT_PEERS }}"'

- name: Index all keys (needed for IBC)
  lineinfile:
    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
    state: present
    regexp: '^index_all_keys *='
    line: 'index_all_keys = true'

- name: Set addr_book_strict=false
  lineinfile:
    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
    state: present
    regexp: '^addr_book_strict *='
    line: 'addr_book_strict = false'

- name: "check if prometheus-tendermint.txt exists"
  delegate_to: localhost
  stat:
    path: "{{ SETUP_HOME }}/prometheus-tendermint.txt"
  register: "prommint"

# NOTE: This is protected by the server firewall
#- name: Set prometheus_listen_addr=127.0.0.1:26660
#  lineinfile:
#    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
#    state: present
#    regexp: '^prometheus_listen_addr *='
#    line: 'prometheus_listen_addr = "127.0.0.1:26660"'

- name: Set prometheus=true
  lineinfile:
    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
    state: present
    regexp: '^prometheus *='
    line: 'prometheus = true'
  when: prommint.stat.exists

- name: Set prometheus=false
  lineinfile:
    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
    state: present
    regexp: '^prometheus *='
    line: 'prometheus = false'
  when: not prommint.stat.exists

- name: Listen for public RPC
  lineinfile:
    path: "/home/{{ service }}/.{{ service }}/config/config.toml"
    state: present
    regexp: '^laddr *= *".*:26657"'
    line: 'laddr = "tcp://0.0.0.0:26657"'
