---
- name: Synchronize helper
  synchronize:
    src: '{{HELPER_BINARY}}'
    dest: /usr/local/bin/
    mode: push
    use_ssh_args: true
  when: HELPER_BINARY is defined

- name: Synchronize Agoric SDK
  synchronize:
    src: '{{ AGORIC_SDK }}/'
    dest: '/usr/src/agoric-sdk/'
    dirs: yes
    delete: yes
    checksum: yes
    mode: push
    use_ssh_args: true

- name: 'Symlink ag-chain-cosmos'
  file:
    src: '/usr/src/agoric-sdk/packages/cosmic-swingset/bin/ag-chain-cosmos'
    dest: '/usr/local/bin/ag-chain-cosmos'
    state: link

- name: 'Symlink ag-solo'
  file:
    src: '/usr/src/agoric-sdk/packages/solo/bin/ag-solo'
    dest: '/usr/local/bin/ag-solo'
    state: link
