---
- hosts: all
  gather_facts: no
  become: no
  serial: 1
  vars:
    ssh_known_hosts: '{{ SETUP_HOME }}/provision/ssh_known_hosts'
  tasks:
    - name: get port and host, default 22
      delegate_to: localhost
      set_fact:
        ansible_ssh_port: "{{ hostvars[inventory_hostname]['ansible_ssh_port'] | default('22') }}"
        ansible_hostname: "{{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}"

    - name: scan SSH host keys
      delegate_to: localhost
      set_fact:
        ssh_keys: "{{ lookup('pipe', 'ssh-keyscan -p' + ansible_ssh_port + ' ' + ansible_hostname) }}"

    - name: ensure host keys were returned
      delegate_to: localhost
      assert:
        that: '{{ (ssh_keys | length) > 0 }}'

    - name: ensure host keys exist in file
      delegate_to: localhost
      lineinfile:
        path: '{{ ssh_known_hosts }}'
        create: yes
        state: present
        line: '{{ item }}'
      with_items: '{{ ssh_keys.splitlines() }}'

    - name: Set master authorized SSH key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', SETUP_HOME + '/id_ecdsa.pub') }}"
