version: v2
plugins:
  - local:
      [
        "go",
        "tool",
        "protoc-gen-openapiv2",
      ]
    out: ../tmp-swagger-gen
    opt:
      - logtostderr=true
      - openapi_naming_strategy=fqn
      - json_names_for_fields=false
      - generate_unbound_methods=true
