name: Lint check

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on:
 push:
   branches: [master]
 pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # FIXME: Reenable after 2020-04-01 when Github cache doesn't take forever.
    #- name: cache node modules
    #  uses: actions/cache@v1
    #  with:
    #    path: ~/.cache/yarn
    #    key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
    #    restore-keys: |
    #      ${{ runner.os }}-yarn-

    # 'yarn install' must be done at the top level, to build all the
    # cross-package symlinks
    - name: yarn install
      run: yarn install
    # 'yarn build' loops over all workspaces
    - name: yarn build
      run: yarn build

    # 'yarn lint-check' just checks the lint where desired
    - name: lint check
      run: yarn lint-check
