name: Test Dapp Encouragement

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on:
 push:
   branches: [master]
 pull_request:

jobs:
  dapp-encouragement:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.14.1', '12.x', '14.x']
    steps:

    - name: Checkout agoric-sdk
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # Select a branch on dapp-encouragement to test against by adding text to the body of the
    # pull request. For example: #dapp-encouragement-branch: zoe-release-0.7.0
    # The default is 'master'
    - name: Get the appropriate dapp-encouragement branch
      id: get-branch
      uses: actions/github-script@0.9.0
      with:
        result-encoding: string
        script: |
          let branch = 'master';
          if (context.payload.pull_request) {
            const { body } = context.payload.pull_request;
            const regex = /.*\#dapp-encouragement-branch:\s+(\S+)/;
            const result = regex.exec(body);
            if (result) {
              branch = result[1];
            }
          }
          console.log(branch);
          return branch;

    - name: yarn install
      run: yarn install
    - name: check dependencies
      run: yarn check-dependencies
    # 'yarn build' loops over all workspaces
    - name: yarn build
      run: yarn build
    - name: yarn link
      run: |
        yarn link-cli ~/bin/agoric
        echo "/home/runner/bin" >> $GITHUB_PATH

    - name: Check out dapp-encouragement
      uses: actions/checkout@v2
      with:
        repository: Agoric/dapp-encouragement
        path: dapp-encouragement
        ref: ${{steps.get-branch.outputs.result}}

    - name: Agoric install in dapp-encouragement
      run: agoric install
      working-directory: ./dapp-encouragement

    - name: yarn build in dapp-encouragement
      run: yarn build
      working-directory: ./dapp-encouragement
    
    - name: yarn test in dapp-encouragement
      run: yarn test
      working-directory: ./dapp-encouragement
